/*the following commands will insert or delete from configuration lists*/
INSERT INTO RICE_TYPE(TYPE_ID, TYPE_NAME, UPCHARGE, AVAILABLE) VALUES (?, ?);
SELECT * FROM RICE_TYPE WHERE AVAILABLE EQUALS TRUE;
DELETE FROM RICE_TYPE WHERE TYPE_ID = ?;

INSERT INTO SAUSE_TYPE(TYPE_ID, SAUSE_NAME, UPCHARGE, AVAILABLE) VALUES(?, ?, ?, ?);
SELECT * FROM SAUSE_TYPE WHERE TYPE_ID = ?;
DELETE FROM SAUSE_TYPE WHERE TYPE_ID = ?;

INSERT INTO BOWL_SIZES(TYPE_ID, TYPE_NAME, SIZE_PRICE) VALUES(?, ?, ?);
SELECT * FROM BOWL_SIZES;
DELETE FROM BOWL_SIZES WHERE TYPE_ID = ?;

INSERT INTO INGREDIANT_TYPE(TYPE_ID, INGREDIANT_NAME, UPCHARGE, RATIO, AVAILABLE) VALUES(?, ?, ?, ?, ?);
SELECT * FROM INGREDIANT_TYPE WHERE AVAILABLE EQUALS TRUE;
DELETE FROM INGREDIATE_TYPE WHERE TYPE_ID = ?;

INSERT INTO APPETIZER_TYPE(TYPE_ID, APPETIZER_NAME, APPETIZER_PRICE) VALUES(?, ?, ?);
SELECT * FROM APPETIZER_TYPE WHERE TYPE_ID = ?;
DELETE FROM APPETIZER_TYPE WHERE TYPE_ID = ?;

INSERT INTO PAYMENT_TYPE(ORDER_NUMBER, PAYMENT_TYPE) VALUES(?, ?);
SELECT * FROM PAYMENT_TYPE
DELETE FROM PAYMENT_TYPE WHERE ORDER_NUMBER = ?;

/*the following commands are used to manage orders*/

INSERT INTO ORDERS(ORDER_NUMBER, ORDER_PRICE, PICKUP_TIME, STATUS_CODE) VALUES(?, ?, ? , ?);
UPDATE ORDERS SET ORDER_STATUS = ? WHERE ORDER_NUMBER = ?;
DELETE FROM ORDERS WHERE ORDER_NUMBER = ?;

INSERT INTO BOWLS(ORDER_NUMBER, BOWL_NUMBER, BOWL_PRICE, BOWL_SIZE, RICE_TYPE, SAUSE_TYPE)
	VALUES(?, ?, ?, ?, ?, ?);
DELETE FROM BOWLS WHERE ORDER_NUMBER = ? AND BOWL_NUMBER = ?;
    
INSERT INTO BOWL_INGREDIANTS(ORDER_NUMBER, BOWL_NUMBER, INGREDIANT_TYPE) VALUES(?,  ?,  ?);
DELETE FROM BOWL_INGREDIATES WHERE ORDER_NUMBER = ? AND BOWL_NUMBER = ? AND INGREDIANT_TYPE = ?;

INSERT INTO APPETIZERS(ORDER_NUMBER, APPETIZER_NUMBER, NUMBER_ORDERED) VALUES (?, ?, ?);
UPDATE APPETIZERS SET NUMBER_ORDERED = ? WHERE ORDER_NUMBER = ? AND APPETIZER_NUMBER = ?;
DELETE FROM APPETIZERS WHERE ORDER_NUMBER = ? AND APPETIZER_NUMBER = ?;

INSERT INTO PAYMENTS(ORDER_NUMBER, PAYMENT_TYPE) VALUES(?, ?);
DELETE FROM PAYMENTS WHERE ORDER_NUMBER = ?;

INSERT INTO CARD_INFO(ORDER_NUMBER, F_NAME, L_NAME, ADDRESS, CARD_NUMBER, CCV, CARD_ZIP)
	VALUES(?, ?, ?, ?, ?, ?, ?);
DELETE FROM CARD_INFO WHERE ORDER_NUMBER = ?;


SELECT * FROM ORDERS WHERE STATUS_CODE EQUALS ?;
SELECT * FROM BOWLS WHERE ORDER_NUMBER EQUALS ?;
SELECT * FROM BOWL_INGREDIANTS WHERE ORDER_NUMBER EQUALS ?;
SELECT * FROM APPETIZERS WHERE ORDER_NUMBER EQUALS ?;
SELECT * FROM PAYMENTS WHERE ORDER_NUMBER EQUALS ?;
SELECT * FROM CARD_INFO WHERE ORDER_NUMBER EQUALS ?;
UPDATE ORDERS SET ORDER_STATUS = ? WHERE ORDER_NUMBER = ?