CREATE TABLE ORDER_STATUS(
	STATUS_CODE INTEGER NOT NULL,
    STATUS_NAME VARCHAR(20) NOT NULL,
    
    PRIMARY KEY (STATUS_CODE)
);

CREATE TABLE ORDERS(
  ORDER_NUMBER INTEGER NOT NULL,
  ORDER_NAME VARCHAR(20),
  ORDER_PRICE DECIMAL(6, 2) NOT NULL,
  PICKUP_TIME DATETIME NOT NULL,
  STATUS_CODE INTEGER NOT NULL,
  
  PRIMARY KEY (ORDER_NUMBER),
  FOREIGN KEY (STATUS_CODE) REFERENCES ORDER_STATUS(STATUS_CODE)
);

CREATE TABLE RICE_TYPE(
	TYPE_ID INTEGER NOT NULL,
	TYPE_NAME VARCHAR(20) NOT NULL,
    UPCHARGE DECIMAL(6, 2) NOT NULL,
    AVAILABLE BOOL NOT NULL,
    
    PRIMARY KEY(TYPE_ID)
);

CREATE TABLE SAUCE_TYPE(
	TYPE_ID INTEGER NOT NULL,
    SAUCE_NAME VARCHAR(20) NOT NULL,
    UPCHARGE DECIMAL(6, 2) NOT NULL,
    AVAILABLE BOOL NOT NULL,
    
    PRIMARY KEY(TYPE_ID)
);

CREATE TABLE BOWL_SIZES(
	TYPE_ID INTEGER NOT NULL,
    SIZE_NAME VARCHAR (20) NOT NULL,
    SIZE_PRICE DECIMAL(6, 2) NOT NULL,
    
    PRIMARY KEY(TYPE_ID)
);

CREATE TABLE BOWLS(
	ORDER_NUMBER INTEGER NOT NULL,
	BOWL_NUMBER INTEGER NOT NULL,
    BOWL_PRICE DECIMAL(6, 2) NOT NULL,
    BOWL_SIZE INTEGER NOT NULL,
    RICE_TYPE INTEGER NOT NULL,
    SAUCE_TYPE INTEGER NOT NULL,
    
    PRIMARY KEY(ORDER_NUMBER, BOWL_NUMBER),
    FOREIGN KEY(RICE_TYPE) REFERENCES RICE_TYPE(TYPE_ID),
    FOREIGN KEY(SAUCE_TYPE) REFERENCES SAUCE_TYPE(TYPE_ID),
    FOREIGN KEY(BOWL_SIZE) REFERENCES BOWL_SIZES(TYPE_ID)
);

CREATE TABLE INGREDIENT_TYPE(
	TYPE_ID INTEGER NOT NULL,
    INGREDIENT_NAME VARCHAR(20) NOT NULL,
    UPCHARGE DECIMAL(6, 2) NOT NULL,
    RATIO INTEGER NOT NULL,
    AVAILABLE BOOL NOT NULL,
    
    PRIMARY KEY(TYPE_ID)
);

CREATE TABLE BOWL_INGREDIENTS(
	ORDER_NUMBER INTEGER NOT NULL,
	BOWL_NUMBER INTEGER NOT NULL,
    INGREDIENT_TYPE INTEGER NOT NULL,
    
    PRIMARY KEY(ORDER_NUMBER, BOWL_NUMBER, INGREDIENT_TYPE),
    FOREIGN KEY(ORDER_NUMBER, BOWL_NUMBER) REFERENCES BOWLS(ORDER_NUMBER, BOWL_NUMBER),
    FOREIGN KEY(INGREDIENT_TYPE) REFERENCES INGREDIENT_TYPE(TYPE_ID)
);

CREATE TABLE APPETIZER_TYPE(
	TYPE_ID INTEGER NOT NULL,
    APPETIZER_NAME VARCHAR(20) NOT NULL,
    APPETIZER_PRICE DECIMAL(6, 2) NOT NULL,
    
    PRIMARY KEY(TYPE_ID)
);

CREATE TABLE APPETIZERS(
	ORDER_NUMBER INTEGER NOT NULL,
    APPETIZER_NUMBER INTEGER NOT NULL,
    NUMBER_ORDERED INTEGER NOT NULL,
    
    PRIMARY KEY(ORDER_NUMBER, APPETIZER_NUMBER),
    FOREIGN KEY(ORDER_NUMBER) REFERENCES ORDERS(ORDER_NUMBER),
    FOREIGN KEY(APPETIZER_NUMBER) REFERENCES APPETIZER_TYPE(TYPE_ID)
);

CREATE TABLE PAYMENT_TYPE(
	TYPE_ID INTEGER NOT NULL,
    PAYMENT_NAME VARCHAR(20) NOT NULL,
    
    PRIMARY KEY(TYPE_ID)
);

CREATE TABLE CARD_INFO(
	ORDER_NUMBER INTEGER NOT NULL,
    F_NAME VARCHAR(30),
    L_NAME VARCHAR(30),
    ADDRESS VARCHAR(100),
    CARD_NUMBER INTEGER(16) NOT NULL,
    CCV INTEGER(4) NOT NULL,
    CARD_ZIP INTEGER(5),
    
    PRIMARY KEY(ORDER_NUMBER),
    FOREIGN KEY(ORDER_NUMBER) REFERENCES ORDERS(ORDER_NUMBER)
);

CREATE TABLE PAYMENTS(
	ORDER_NUMBER INTEGER NOT NULL,
    PAYMENT_TYPE INTEGER NOT NULL,
    
    PRIMARY KEY(ORDER_NUMBER),
    FOREIGN KEY(PAYMENT_TYPE) REFERENCES PAYMENT_TYPE(TYPE_ID)
);

INSERT INTO BOWL_SIZES(TYPE_ID, SIZE_NAME, SIZE_PRICE) VALUES(0, "small", 1);
INSERT INTO BOWL_SIZES(TYPE_ID, SIZE_NAME, SIZE_PRICE) VALUES(1, "medium", 2);
INSERT INTO BOWL_SIZES(TYPE_ID, SIZE_NAME, SIZE_PRICE) VALUES(2, "large", 3);

INSERT INTO ORDER_STATUS(STATUS_CODE, STATUS_NAME) VALUES(0, "waiting");
INSERT INTO ORDER_STATUS(STATUS_CODE, STATUS_NAME) VALUES(1, "readyForPickup");
INSERT INTO ORDER_STATUS(STATUS_CODE, STATUS_NAME) VALUES(2, "completed");
INSERT INTO ORDER_STATUS(STATUS_CODE, STATUS_NAME) VALUES(3, "canceled");

INSERT INTO PAYMENT_TYPE(TYPE_ID, PAYMENT_NAME) VALUES(0, "cash");
INSERT INTO PAYMENT_TYPE(TYPE_ID, PAYMENT_NAME) VALUES(1, "card");